### PR TITLE
Fix broken import with Django 1.8

### PR DESCRIPTION
**Pull request by meastman**

### CODE REVIEW

**Comment by frewsxcv** [comment]
If this is the only fix needed to get this working with Django 1.8, you could add 1.8 to the .travis.yml file so it also gets tested there, unless you plan to do that in a followup pr

**Comment by frewsxcv** [comment]
Also, there are apparently merge conflicts?

**Comment by meastman** [comment]
> Also, there are apparently merge conflicts?

My bad; rebased off master now.

**Comment by frewsxcv** [comment]
LGTM

**Pull request merged**
