### PR TITLE
Document v1.0 changes

### LINKED ISSUE #32: Document 1.0 changes in CHANGES file

### PR DESCRIPTION
**Pull request by meastman**
Fixes #32

### CODE REVIEW

**Comment by meastman** [comment]
Reviewable

**Comment by frewsxcv** [comment]
How about https://github.com/educreations/django-ormcache/commit/81056346dd49c9ca5a9dfc3f5136dad5bd70ae60 ?

**Comment by frewsxcv** [comment]
Other than that, LGTM

**Comment by meastman** [comment]
> How about 8105634 ?

That's the implementation of "Support ForeignKey lookups (when use_for_related_fields = True is set on the manager)". I added another statement about using `.filter(pk=).get()` directly and the Django 1.7+ requirement for that lookup.

**Comment by frewsxcv** [comment]
LGTM

**Pull request merged**
